/********************************************************************
* G__KVMultiDetglobvars.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__KVMultiDetglobvars.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__KVMultiDetglobvars();
extern void G__cpp_setup_inheritanceG__KVMultiDetglobvars();
extern void G__cpp_setup_typetableG__KVMultiDetglobvars();
extern void G__cpp_setup_memvarG__KVMultiDetglobvars();
extern void G__cpp_setup_globalG__KVMultiDetglobvars();
extern void G__cpp_setup_memfuncG__KVMultiDetglobvars();
extern void G__cpp_setup_funcG__KVMultiDetglobvars();
extern void G__set_cpp_environmentG__KVMultiDetglobvars();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVEkin.h"
#include "KVQuadMoment.h"
#include "KVZtotAv.h"
#include "KVTensPCM.h"
#include "KVFlowTensor.h"
#include "KVTensE.h"
#include "KVMultIMFAv.h"
#include "KVMultAv.h"
#include "KVVarGlobMean.h"
#include "KVPtot.h"
#include "KVCalorimetry.h"
#include "KVZmean.h"
#include "KVEtransLCP.h"
#include "KVSource.h"
#include "KVMultLeg.h"
#include "KVCaloBase.h"
#include "KVZmax.h"
#include "KVMultLegAv.h"
#include "KVVarGlob.h"
#include "KVZtot.h"
#include "KVTenseur3.h"
#include "KVZbound.h"
#include "KVEtrans.h"
#include "KVFoxH2.h"
#include "KVZBoundMean.h"
#include "KVVarGlob1.h"
#include "KVMultIMF.h"
#include "KVRiso.h"
#include "KVRisoAv.h"
#include "KVVGSum.h"
#include "KVGVList.h"
#include "KVRelativeVelocity.h"
#include "KVZboundAv.h"
#include "KVZVtot.h"
#include "KVTensP.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TClass;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TBuffer;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMemberInspector;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TObject;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TNamed;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TCollection;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TString;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TList;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVString;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVBase;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TRotation;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TVector3;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TSeqCollection;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVSeqCollection;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVList;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVNameValueList;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVParticleCondition;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVNucleus;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVClassFactory;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVEvent;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVVarGlob;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVVarGlobcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVVarGlob1;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVEkin;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVQuadMoment;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZtot;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZtotAv;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVTenseur3;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVTensP;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVTensPCM;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVFlowTensor;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVFlowTensorcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVTensE;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZbound;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZboundcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVMultIMF;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVMultIMFAv;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVMultAv;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVVarGlobMean;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVPtot;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVCaloBase;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVCalorimetry;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZmean;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVEtrans;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVEtransLCP;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVSource;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVMultLeg;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZmax;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVMultLegAv;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVFoxH2;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZBoundMean;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVRiso;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVRisoAv;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TMethodCall;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVVGSum;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVVGSumcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_TTree;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVGVList;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVRelativeVelocity;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZboundAv;
extern G__linked_taginfo G__G__KVMultiDetglobvarsLN_KVZVtot;

/* STUB derived class for protected member access */
