/********************************************************************
* G__VAMOSreconstruction.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__VAMOSreconstruction.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__VAMOSreconstruction();
extern void G__cpp_setup_inheritanceG__VAMOSreconstruction();
extern void G__cpp_setup_typetableG__VAMOSreconstruction();
extern void G__cpp_setup_memvarG__VAMOSreconstruction();
extern void G__cpp_setup_globalG__VAMOSreconstruction();
extern void G__cpp_setup_memfuncG__VAMOSreconstruction();
extern void G__cpp_setup_funcG__VAMOSreconstruction();
extern void G__set_cpp_environmentG__VAMOSreconstruction();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ReconstructionSeDv.h"
#include "KVVAMOSReconTrajectory.h"
#include "Reconstructionv.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__VAMOSreconstructionLN_TClass;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TBuffer;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMemberInspector;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TObject;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TNamed;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_LogFile;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_Random;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TTree;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_SeD12v;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_ReconstructionSeDv;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_KVBase;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_TVector3;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_KVVAMOSReconTrajectory;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_KVVAMOSReconTrajectorycLcLdA;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_DriftChamberv;
extern G__linked_taginfo G__G__VAMOSreconstructionLN_Reconstructionv;

/* STUB derived class for protected member access */
