
/* Includes added by #pragma extra_include */
#include "Rtypes.h"
/********************************************************************
* G__KVMultiDetbase.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__KVMultiDetbase.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__KVMultiDetbase();
extern void G__cpp_setup_inheritanceG__KVMultiDetbase();
extern void G__cpp_setup_typetableG__KVMultiDetbase();
extern void G__cpp_setup_memvarG__KVMultiDetbase();
extern void G__cpp_setup_globalG__KVMultiDetbase();
extern void G__cpp_setup_memfuncG__KVMultiDetbase();
extern void G__cpp_setup_funcG__KVMultiDetbase();
extern void G__set_cpp_environmentG__KVMultiDetbase();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVRungeKutta.h"
#include "KVDatime.h"
#include "KVPartition.h"
#include "KVNamedParameter.h"
#include "KVCouple.h"
#include "KVSystemDirectory.h"
#include "KVPartitionList.h"
#include "KVRList.h"
#include "KVDatedFileManager.h"
#include "KVClassMonitor.h"
#include "KVCVSUpdateChecker.h"
#include "KVBase.h"
#include "KVBQSLogReader.h"
#include "KVTarArchive.h"
#include "KVGELogReader.h"
#include "KVHistogram.h"
#include "KVMemoryChunk.h"
#include "KVLockfile.h"
#include "KVPartitionFunction.h"
#include "Hexa_t.h"
#include "KVValues.h"
#include "KVNameValueList.h"
#include "KVHistoManipulator.h"
#include "KVPosition.h"
#include "KVUnits.h"
#include "KVString.h"
#include "KVSeqCollection.h"
#include "Binary_t.h"
#include "KVColouredBase.h"
#include "KVUniqueNameList.h"
#include "KVUpdateChecker.h"
#include "KVDataBranchHandler.h"
#include "KVEnv.h"
#include "KVNumberList.h"
#include "KVIntegerList.h"
#include "KVEventListMaker.h"
#include "KVList.h"
#include "KVSystemFile.h"
#include "KVHashList.h"
#include "KVLogReader.h"
#include "KVFileReader.h"
#include "KVPartitionFromLeaf.h"
#include "KVMemoryPool.h"
#include "KVClassFactory.h"
#include "KVPartitionGenerator.h"

#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__KVMultiDetbaseLN_TClass;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TBuffer;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMemberInspector;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TObject;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TNamed;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TCollection;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TString;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TObjArray;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMethod;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TProcessID;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TRegexp;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TPRegexp;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVString;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVLockfile;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TPluginHandler;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVBase;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVBasecLcLEKaliVedaBits;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVRungeKutta;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TDatime;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVDatime;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVDatimecLcLEKVDateFormat;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TArrayI;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVIntegerList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVIntegerListcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TIterator;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TSeqCollection;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TQObjSender;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TFile;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_THashTable;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVSeqCollection;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVSeqCollectioncLcLdA;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVHashList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVNamedParameter;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVNamedParametercLcLdA;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVEnv;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVNameValueList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVNumberList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVValues;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVPartition;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVCouple;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TSystemFile;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TSystemDirectory;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVSystemDirectory;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVUniqueNameList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TTree;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVPartitionList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TRefArray;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVRList;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVSortableDatedFile;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVDatedFileManager;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TEnv;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_EEnvLevel;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVClassMonitor;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVUpdateChecker;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVCVSUpdateChecker;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVLogReader;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVBQSLogReader;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVTarArchive;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVGELogReader;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TAxis;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TAttLine;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TAttMarker;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TF1;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TH1;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TGraph;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TH2;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TCutG;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVHistogram;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVMemoryChunk;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVPartitionFunction;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_Hexa_t;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TProfile;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TGraphErrors;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TCanvas;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMultiGraph;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVHistoManipulator;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TRotation;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TVector3;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TGeoHMatrix;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TGeoBBox;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVPosition;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVUnits;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVColouredBase;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TLeaf;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_TBranch;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVDataBranchHandler;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVEventListMaker;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_FileStat_t;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_UserGroup_t;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVSystemFile;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVFileReader;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVPartitionFromLeaf;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVMemoryPool;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVClassMember;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVClassMethod;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVClassFactory;
extern G__linked_taginfo G__G__KVMultiDetbaseLN_KVPartitionGenerator;

/* STUB derived class for protected member access */
typedef Binary_t<unsigned char> G__Binary_tlEunsignedsPchargR;
typedef Binary_t<unsigned short> G__Binary_tlEunsignedsPshortgR;
typedef Binary_t<unsigned int> G__Binary_tlEunsignedsPintgR;
typedef Binary_t<long long> G__Binary_tlElongsPlonggR;
