/********************************************************************
* G__VAMOSdb.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__VAMOSdb.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__VAMOSdb();
extern void G__cpp_setup_inheritanceG__VAMOSdb();
extern void G__cpp_setup_typetableG__VAMOSdb();
extern void G__cpp_setup_memvarG__VAMOSdb();
extern void G__cpp_setup_globalG__VAMOSdb();
extern void G__cpp_setup_memfuncG__VAMOSdb();
extern void G__cpp_setup_funcG__VAMOSdb();
extern void G__set_cpp_environmentG__VAMOSdb();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVIVDB.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__VAMOSdbLN_TClass;
extern G__linked_taginfo G__G__VAMOSdbLN_TBuffer;
extern G__linked_taginfo G__G__VAMOSdbLN_TMemberInspector;
extern G__linked_taginfo G__G__VAMOSdbLN_TObject;
extern G__linked_taginfo G__G__VAMOSdbLN_TNamed;
extern G__linked_taginfo G__G__VAMOSdbLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__VAMOSdbLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__VAMOSdbLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__VAMOSdbLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSdbLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__VAMOSdbLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TFolder;
extern G__linked_taginfo G__G__VAMOSdbLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__VAMOSdbLN_KVDBTable;
extern G__linked_taginfo G__G__VAMOSdbLN_KVDataBase;
extern G__linked_taginfo G__G__VAMOSdbLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__VAMOSdbLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__VAMOSdbLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__VAMOSdbLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__VAMOSdbLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__VAMOSdbLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__VAMOSdbLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__VAMOSdbLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__VAMOSdbLN_KVINDRARunListReader;
extern G__linked_taginfo G__G__VAMOSdbLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__VAMOSdbLN_KVINDRADB;
extern G__linked_taginfo G__G__VAMOSdbLN_KVIVDB;

/* STUB derived class for protected member access */
