/********************************************************************
* G__FAZIAdb.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__FAZIAdb.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__FAZIAdb();
extern void G__cpp_setup_inheritanceG__FAZIAdb();
extern void G__cpp_setup_typetableG__FAZIAdb();
extern void G__cpp_setup_memvarG__FAZIAdb();
extern void G__cpp_setup_globalG__FAZIAdb();
extern void G__cpp_setup_memfuncG__FAZIAdb();
extern void G__cpp_setup_funcG__FAZIAdb();
extern void G__set_cpp_environmentG__FAZIAdb();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVFAZIADB.h"
#include "KVFAZIADBRun.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__FAZIAdbLN_TClass;
extern G__linked_taginfo G__G__FAZIAdbLN_TBuffer;
extern G__linked_taginfo G__G__FAZIAdbLN_TMemberInspector;
extern G__linked_taginfo G__G__FAZIAdbLN_TObject;
extern G__linked_taginfo G__G__FAZIAdbLN_TNamed;
extern G__linked_taginfo G__G__FAZIAdbLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__FAZIAdbLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__FAZIAdbLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TList;
extern G__linked_taginfo G__G__FAZIAdbLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__FAZIAdbLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TFolder;
extern G__linked_taginfo G__G__FAZIAdbLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__FAZIAdbLN_KVSeqCollection;
extern G__linked_taginfo G__G__FAZIAdbLN_KVDBRecord;
extern G__linked_taginfo G__G__FAZIAdbLN_KVDBTable;
extern G__linked_taginfo G__G__FAZIAdbLN_KVDataBase;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__FAZIAdbLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__FAZIAdbLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAdbLN_KVNumberList;
extern G__linked_taginfo G__G__FAZIAdbLN_KVDBSystem;
extern G__linked_taginfo G__G__FAZIAdbLN_KVDBRun;
extern G__linked_taginfo G__G__FAZIAdbLN_KVFAZIADBRun;
extern G__linked_taginfo G__G__FAZIAdbLN_KVFAZIADB;

/* STUB derived class for protected member access */
