/********************************************************************
* G__FAZIAanalysis.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__FAZIAanalysis.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__FAZIAanalysis();
extern void G__cpp_setup_inheritanceG__FAZIAanalysis();
extern void G__cpp_setup_typetableG__FAZIAanalysis();
extern void G__cpp_setup_memvarG__FAZIAanalysis();
extern void G__cpp_setup_globalG__FAZIAanalysis();
extern void G__cpp_setup_memfuncG__FAZIAanalysis();
extern void G__cpp_setup_funcG__FAZIAanalysis();
extern void G__set_cpp_environmentG__FAZIAanalysis();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVFAZIAReconDataAnalyser.h"
#include "KVFAZIARawDataReader.h"
#include "KVFAZIARawDataReconstructor.h"
#include "KVFAZIARawDataAnalyser.h"
#include "KVFAZIASelector.h"
#include "KVFAZIAReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__FAZIAanalysisLN_TClass;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TBuffer;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMemberInspector;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TObject;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TString;
extern G__linked_taginfo G__G__FAZIAanalysisLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TList;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TObjArray;
extern G__linked_taginfo G__G__FAZIAanalysisLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TTree;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TFile;
extern G__linked_taginfo G__G__FAZIAanalysisLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TSelector;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVNumberList;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVString;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVDataAnalyser;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TEnv;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVDataPatchList;
extern G__linked_taginfo G__G__FAZIAanalysisLN_TChain;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVFAZIAReconDataAnalyser;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVFAZIARawEvent;
extern G__linked_taginfo G__G__FAZIAanalysisLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVDetectorEvent;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVFAZIAReader;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVFAZIARawDataReader;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVReconstructedEvent;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVFAZIARawDataReconstructor;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVFAZIARawDataAnalyser;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVEventSelector;
extern G__linked_taginfo G__G__FAZIAanalysisLN_KVFAZIASelector;

/* STUB derived class for protected member access */
