/********************************************************************
* G__MicroStatweights.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__MicroStatweights.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__MicroStatweights();
extern void G__cpp_setup_inheritanceG__MicroStatweights();
extern void G__cpp_setup_typetableG__MicroStatweights();
extern void G__cpp_setup_memvarG__MicroStatweights();
extern void G__cpp_setup_globalG__MicroStatweights();
extern void G__cpp_setup_memfuncG__MicroStatweights();
extern void G__cpp_setup_funcG__MicroStatweights();
extern void G__set_cpp_environmentG__MicroStatweights();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "mcweight.h"
#include "StatWeight.h"
#include "mdweight.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__MicroStatweightsLN_TClass;
extern G__linked_taginfo G__G__MicroStatweightsLN_TBuffer;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMemberInspector;
extern G__linked_taginfo G__G__MicroStatweightsLN_TObject;
extern G__linked_taginfo G__G__MicroStatweightsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_KVHashList;
extern G__linked_taginfo G__G__MicroStatweightsLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_KVNucleus;
extern G__linked_taginfo G__G__MicroStatweightsLN_KVEvent;
extern G__linked_taginfo G__G__MicroStatweightsLN_iteratorlEinput_iterator_tagcOKVNucleuscOlongcOKVNucleusmUcOKVNucleusaNgR;
extern G__linked_taginfo G__G__MicroStatweightsLN_MicroStat;
extern G__linked_taginfo G__G__MicroStatweightsLN_MicroStatcLcLStatWeight;
extern G__linked_taginfo G__G__MicroStatweightsLN_MicroStatcLcLmcweight;
extern G__linked_taginfo G__G__MicroStatweightsLN_TF1;
extern G__linked_taginfo G__G__MicroStatweightsLN_MicroStatcLcLmdweight;

/* STUB derived class for protected member access */
