/********************************************************************
* G__VAMOScalibration.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__VAMOScalibration.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__VAMOScalibration();
extern void G__cpp_setup_inheritanceG__VAMOScalibration();
extern void G__cpp_setup_typetableG__VAMOScalibration();
extern void G__cpp_setup_memvarG__VAMOScalibration();
extern void G__cpp_setup_globalG__VAMOScalibration();
extern void G__cpp_setup_memfuncG__VAMOScalibration();
extern void G__cpp_setup_funcG__VAMOScalibration();
extern void G__set_cpp_environmentG__VAMOScalibration();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVSeDPositionCal.h"
#include "KVLightEnergyCsIVamos.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__VAMOScalibrationLN_TClass;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TBuffer;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMemberInspector;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TObject;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TNamed;
extern G__linked_taginfo G__G__VAMOScalibrationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_KVBase;
extern G__linked_taginfo G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TF1;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_KVDetector;
extern G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__VAMOScalibrationLN_KVCalibrator;
extern G__linked_taginfo G__G__VAMOScalibrationLN_KVSeDPositionCal;
extern G__linked_taginfo G__G__VAMOScalibrationLN_KVLightEnergyCsI;
extern G__linked_taginfo G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos;

/* STUB derived class for protected member access */
