//
// File generated by rootcint at Fri Jul 17 15:54:13 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME G__VAMOScalibration
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G__VAMOScalibration.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void KVSeDPositionCal_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_KVSeDPositionCal(void *p = 0);
   static void *newArray_KVSeDPositionCal(Long_t size, void *p);
   static void delete_KVSeDPositionCal(void *p);
   static void deleteArray_KVSeDPositionCal(void *p);
   static void destruct_KVSeDPositionCal(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::KVSeDPositionCal*)
   {
      ::KVSeDPositionCal *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::KVSeDPositionCal >(0);
      static ::ROOT::TGenericClassInfo 
         instance("KVSeDPositionCal", ::KVSeDPositionCal::Class_Version(), "/home/john/software/sources/kaliveda.git/VAMOS/calibration/KVSeDPositionCal.h", 13,
                  typeid(::KVSeDPositionCal), ::ROOT::DefineBehavior(ptr, ptr),
                  &::KVSeDPositionCal::Dictionary, isa_proxy, 4,
                  sizeof(::KVSeDPositionCal) );
      instance.SetNew(&new_KVSeDPositionCal);
      instance.SetNewArray(&newArray_KVSeDPositionCal);
      instance.SetDelete(&delete_KVSeDPositionCal);
      instance.SetDeleteArray(&deleteArray_KVSeDPositionCal);
      instance.SetDestructor(&destruct_KVSeDPositionCal);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::KVSeDPositionCal*)
   {
      return GenerateInitInstanceLocal((::KVSeDPositionCal*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KVSeDPositionCal*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void KVLightEnergyCsIVamos_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_KVLightEnergyCsIVamos(void *p = 0);
   static void *newArray_KVLightEnergyCsIVamos(Long_t size, void *p);
   static void delete_KVLightEnergyCsIVamos(void *p);
   static void deleteArray_KVLightEnergyCsIVamos(void *p);
   static void destruct_KVLightEnergyCsIVamos(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::KVLightEnergyCsIVamos*)
   {
      ::KVLightEnergyCsIVamos *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::KVLightEnergyCsIVamos >(0);
      static ::ROOT::TGenericClassInfo 
         instance("KVLightEnergyCsIVamos", ::KVLightEnergyCsIVamos::Class_Version(), "/home/john/software/sources/kaliveda.git/VAMOS/calibration/KVLightEnergyCsIVamos.h", 10,
                  typeid(::KVLightEnergyCsIVamos), ::ROOT::DefineBehavior(ptr, ptr),
                  &::KVLightEnergyCsIVamos::Dictionary, isa_proxy, 4,
                  sizeof(::KVLightEnergyCsIVamos) );
      instance.SetNew(&new_KVLightEnergyCsIVamos);
      instance.SetNewArray(&newArray_KVLightEnergyCsIVamos);
      instance.SetDelete(&delete_KVLightEnergyCsIVamos);
      instance.SetDeleteArray(&deleteArray_KVLightEnergyCsIVamos);
      instance.SetDestructor(&destruct_KVLightEnergyCsIVamos);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::KVLightEnergyCsIVamos*)
   {
      return GenerateInitInstanceLocal((::KVLightEnergyCsIVamos*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KVLightEnergyCsIVamos*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr KVSeDPositionCal::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *KVSeDPositionCal::Class_Name()
{
   return "KVSeDPositionCal";
}

//______________________________________________________________________________
const char *KVSeDPositionCal::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::KVSeDPositionCal*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int KVSeDPositionCal::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::KVSeDPositionCal*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void KVSeDPositionCal::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::KVSeDPositionCal*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *KVSeDPositionCal::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::KVSeDPositionCal*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr KVLightEnergyCsIVamos::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *KVLightEnergyCsIVamos::Class_Name()
{
   return "KVLightEnergyCsIVamos";
}

//______________________________________________________________________________
const char *KVLightEnergyCsIVamos::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::KVLightEnergyCsIVamos*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int KVLightEnergyCsIVamos::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::KVLightEnergyCsIVamos*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void KVLightEnergyCsIVamos::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::KVLightEnergyCsIVamos*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *KVLightEnergyCsIVamos::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::KVLightEnergyCsIVamos*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void KVLightEnergyCsIVamos::Streamer(TBuffer &R__b)
{
   // Stream an object of class KVLightEnergyCsIVamos.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(KVLightEnergyCsIVamos::Class(),this);
   } else {
      R__b.WriteClassBuffer(KVLightEnergyCsIVamos::Class(),this);
   }
}

//______________________________________________________________________________
void KVLightEnergyCsIVamos::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class KVLightEnergyCsIVamos.
      TClass *R__cl = ::KVLightEnergyCsIVamos::IsA();
      if (R__cl || R__insp.IsA()) { }
      KVLightEnergyCsI::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_KVLightEnergyCsIVamos(void *p) {
      return  p ? new(p) ::KVLightEnergyCsIVamos : new ::KVLightEnergyCsIVamos;
   }
   static void *newArray_KVLightEnergyCsIVamos(Long_t nElements, void *p) {
      return p ? new(p) ::KVLightEnergyCsIVamos[nElements] : new ::KVLightEnergyCsIVamos[nElements];
   }
   // Wrapper around operator delete
   static void delete_KVLightEnergyCsIVamos(void *p) {
      delete ((::KVLightEnergyCsIVamos*)p);
   }
   static void deleteArray_KVLightEnergyCsIVamos(void *p) {
      delete [] ((::KVLightEnergyCsIVamos*)p);
   }
   static void destruct_KVLightEnergyCsIVamos(void *p) {
      typedef ::KVLightEnergyCsIVamos current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::KVLightEnergyCsIVamos

//______________________________________________________________________________
void KVSeDPositionCal::Streamer(TBuffer &R__b)
{
   // Stream an object of class KVSeDPositionCal.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(KVSeDPositionCal::Class(),this);
   } else {
      R__b.WriteClassBuffer(KVSeDPositionCal::Class(),this);
   }
}

//______________________________________________________________________________
void KVSeDPositionCal::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class KVSeDPositionCal.
      TClass *R__cl = ::KVSeDPositionCal::IsA();
      if (R__cl || R__insp.IsA()) { }
      KVCalibrator::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_KVSeDPositionCal(void *p) {
      return  p ? new(p) ::KVSeDPositionCal : new ::KVSeDPositionCal;
   }
   static void *newArray_KVSeDPositionCal(Long_t nElements, void *p) {
      return p ? new(p) ::KVSeDPositionCal[nElements] : new ::KVSeDPositionCal[nElements];
   }
   // Wrapper around operator delete
   static void delete_KVSeDPositionCal(void *p) {
      delete ((::KVSeDPositionCal*)p);
   }
   static void deleteArray_KVSeDPositionCal(void *p) {
      delete [] ((::KVSeDPositionCal*)p);
   }
   static void destruct_KVSeDPositionCal(void *p) {
      typedef ::KVSeDPositionCal current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::KVSeDPositionCal

/********************************************************
* G__VAMOScalibration.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG__VAMOScalibration();

extern "C" void G__set_cpp_environmentG__VAMOScalibration() {
  G__cpp_reset_tagtableG__VAMOScalibration();
}
#include <new>
extern "C" int G__cpp_dllrevG__VAMOScalibration() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* KVSeDPositionCal */
static int G__G__VAMOScalibration_364_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KVSeDPositionCal* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KVSeDPositionCal[n];
     } else {
       p = new((void*) gvp) KVSeDPositionCal[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KVSeDPositionCal;
     } else {
       p = new((void*) gvp) KVSeDPositionCal;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KVSeDPositionCal* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new KVSeDPositionCal((KVDetector*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) KVSeDPositionCal((KVDetector*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KVSeDPositionCal*) G__getstructoffset())->Compute((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2]), *(Double_t*) G__Doubleref(&libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KVSeDPositionCal*) G__getstructoffset())->operator()((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2]), *(Double_t*) G__Doubleref(&libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) KVSeDPositionCal::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KVSeDPositionCal::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) KVSeDPositionCal::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      KVSeDPositionCal::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KVSeDPositionCal*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KVSeDPositionCal::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KVSeDPositionCal::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KVSeDPositionCal::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_364_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KVSeDPositionCal::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__VAMOScalibration_364_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KVSeDPositionCal* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KVSeDPositionCal(*(KVSeDPositionCal*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KVSeDPositionCal G__TKVSeDPositionCal;
static int G__G__VAMOScalibration_364_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KVSeDPositionCal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KVSeDPositionCal*) (soff+(sizeof(KVSeDPositionCal)*i)))->~G__TKVSeDPositionCal();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KVSeDPositionCal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KVSeDPositionCal*) (soff))->~G__TKVSeDPositionCal();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__VAMOScalibration_364_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KVSeDPositionCal* dest = (KVSeDPositionCal*) G__getstructoffset();
   *dest = *(KVSeDPositionCal*) libp->para[0].ref;
   const KVSeDPositionCal& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* KVLightEnergyCsIVamos */
static int G__G__VAMOScalibration_366_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KVLightEnergyCsIVamos* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KVLightEnergyCsIVamos[n];
     } else {
       p = new((void*) gvp) KVLightEnergyCsIVamos[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KVLightEnergyCsIVamos;
     } else {
       p = new((void*) gvp) KVLightEnergyCsIVamos;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KVLightEnergyCsIVamos* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new KVLightEnergyCsIVamos((KVDetector*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) KVLightEnergyCsIVamos((KVDetector*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const KVLightEnergyCsIVamos*) G__getstructoffset())->Compute((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((KVLightEnergyCsIVamos*) G__getstructoffset())->Invert((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) KVLightEnergyCsIVamos::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KVLightEnergyCsIVamos::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) KVLightEnergyCsIVamos::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      KVLightEnergyCsIVamos::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KVLightEnergyCsIVamos*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KVLightEnergyCsIVamos::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KVLightEnergyCsIVamos::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KVLightEnergyCsIVamos::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__VAMOScalibration_366_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KVLightEnergyCsIVamos::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KVLightEnergyCsIVamos G__TKVLightEnergyCsIVamos;
static int G__G__VAMOScalibration_366_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KVLightEnergyCsIVamos*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KVLightEnergyCsIVamos*) (soff+(sizeof(KVLightEnergyCsIVamos)*i)))->~G__TKVLightEnergyCsIVamos();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KVLightEnergyCsIVamos*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KVLightEnergyCsIVamos*) (soff))->~G__TKVLightEnergyCsIVamos();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* KVSeDPositionCal */

/* KVLightEnergyCsIVamos */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__VAMOScalibration {
 public:
  G__Sizep2memfuncG__VAMOScalibration(): p(&G__Sizep2memfuncG__VAMOScalibration::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__VAMOScalibration::*p)();
};

size_t G__get_sizep2memfuncG__VAMOScalibration()
{
  G__Sizep2memfuncG__VAMOScalibration a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__VAMOScalibration() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal))) {
     KVSeDPositionCal *G__Lderived;
     G__Lderived=(KVSeDPositionCal*)0x1000;
     {
       KVCalibrator *G__Lpbase=(KVCalibrator*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVCalibrator),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       KVBase *G__Lpbase=(KVBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos))) {
     KVLightEnergyCsIVamos *G__Lderived;
     G__Lderived=(KVLightEnergyCsIVamos*)0x1000;
     {
       KVLightEnergyCsI *G__Lpbase=(KVLightEnergyCsI*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsI),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       KVCalibrator *G__Lpbase=(KVCalibrator*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVCalibrator),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       KVBase *G__Lpbase=(KVBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos),G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__VAMOScalibration() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Binary_t<UChar_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_Binary_tlEunsignedsPchargR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Binary_t<UShort_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_Binary_tlEunsignedsPshortgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Binary_t<UInt_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_Binary_tlEunsignedsPintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Binary_t<Long64_t>",117,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_Binary_tlElongsPlonggR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* KVSeDPositionCal */
static void G__setup_memvarKVSeDPositionCal(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal));
   { KVSeDPositionCal *p; p=(KVSeDPositionCal*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* KVLightEnergyCsIVamos */
static void G__setup_memvarKVLightEnergyCsIVamos(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos));
   { KVLightEnergyCsIVamos *p; p=(KVLightEnergyCsIVamos*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TF1),-1,-2,4,"fLightVamos=",0,"function parameterising light output as function of (energy, Z, A)");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__VAMOScalibration() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncKVSeDPositionCal(void) {
   /* KVSeDPositionCal */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal));
   G__memfunc_setup("KVSeDPositionCal",1538,G__G__VAMOScalibration_364_0_1, 105, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KVSeDPositionCal",1538,G__G__VAMOScalibration_364_0_2, 105, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal), -1, 0, 1, 1, 1, 0, "U 'KVDetector' - 0 - det", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Compute",733,(G__InterfaceMethod) NULL,100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "d - 'Double_t' 0 - chan", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("operator()",957,(G__InterfaceMethod) NULL,100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - chan", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Invert",632,(G__InterfaceMethod) NULL,100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - volts", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Compute",733,G__G__VAMOScalibration_364_0_6, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - X d - 'Double_t' 0 - Y "
"d - 'Double_t' 1 - Xcal d - 'Double_t' 1 - Ycal", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("operator()",957,G__G__VAMOScalibration_364_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - X d - 'Double_t' 0 - Y "
"d - 'Double_t' 1 - Xcal d - 'Double_t' 1 - Ycal", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__VAMOScalibration_364_0_8, 85, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&KVSeDPositionCal::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__VAMOScalibration_364_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KVSeDPositionCal::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__VAMOScalibration_364_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&KVSeDPositionCal::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__VAMOScalibration_364_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&KVSeDPositionCal::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__VAMOScalibration_364_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__VAMOScalibration_364_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KVSeDPositionCal::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__VAMOScalibration_364_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KVSeDPositionCal::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__VAMOScalibration_364_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KVSeDPositionCal::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__VAMOScalibration_364_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KVSeDPositionCal::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("KVSeDPositionCal", 1538, G__G__VAMOScalibration_364_0_20, (int) ('i'), G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal), -1, 0, 1, 1, 1, 0, "u 'KVSeDPositionCal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KVSeDPositionCal", 1664, G__G__VAMOScalibration_364_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__VAMOScalibration_364_0_22, (int) ('u'), G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVSeDPositionCal), -1, 1, 1, 1, 1, 0, "u 'KVSeDPositionCal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncKVLightEnergyCsIVamos(void) {
   /* KVLightEnergyCsIVamos */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos));
   G__memfunc_setup("KVLightEnergyCsIVamos",2056,G__G__VAMOScalibration_366_0_1, 105, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KVLightEnergyCsIVamos",2056,G__G__VAMOScalibration_366_0_2, 105, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos), -1, 0, 1, 1, 1, 0, "U 'KVDetector' - 0 - kvd", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Compute",733,(G__InterfaceMethod) NULL,100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "d - 'Double_t' 0 - chan", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Compute",733,G__G__VAMOScalibration_366_0_4, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 8, 
"d - 'Double_t' 0 - - d - 'Double_t' 0 - - "
"d - 'Double_t' 0 - chan", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Invert",632,G__G__VAMOScalibration_366_0_5, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - - d - 'Double_t' 0 - - "
"d - 'Double_t' 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Invert",632,(G__InterfaceMethod) NULL,100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__VAMOScalibration_366_0_7, 85, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&KVLightEnergyCsIVamos::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__VAMOScalibration_366_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KVLightEnergyCsIVamos::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__VAMOScalibration_366_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&KVLightEnergyCsIVamos::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__VAMOScalibration_366_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&KVLightEnergyCsIVamos::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__VAMOScalibrationLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__VAMOScalibration_366_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__VAMOScalibration_366_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KVLightEnergyCsIVamos::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__VAMOScalibration_366_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KVLightEnergyCsIVamos::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__VAMOScalibration_366_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KVLightEnergyCsIVamos::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__VAMOScalibration_366_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KVLightEnergyCsIVamos::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~KVLightEnergyCsIVamos", 2182, G__G__VAMOScalibration_366_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__VAMOScalibration() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__VAMOScalibration() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__VAMOScalibration() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__VAMOScalibrationLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_KVBase = { "KVBase" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_KVDetector = { "KVDetector" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlEunsignedsPchargR = { "Binary_t<unsigned char>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlEunsignedsPshortgR = { "Binary_t<unsigned short>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlEunsignedsPintgR = { "Binary_t<unsigned int>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_Binary_tlElongsPlonggR = { "Binary_t<long long>" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_KVCalibrator = { "KVCalibrator" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_KVSeDPositionCal = { "KVSeDPositionCal" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_KVLightEnergyCsI = { "KVLightEnergyCsI" , 99 , -1 };
G__linked_taginfo G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos = { "KVLightEnergyCsIVamos" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__VAMOScalibration() {
  G__G__VAMOScalibrationLN_TClass.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TBuffer.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMemberInspector.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TObject.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TNamed.tagnum = -1 ;
  G__G__VAMOScalibrationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_KVBase.tagnum = -1 ;
  G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TF1.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_KVDetector.tagnum = -1 ;
  G__G__VAMOScalibrationLN_Binary_tlEunsignedsPchargR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_Binary_tlEunsignedsPshortgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_Binary_tlEunsignedsPintgR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_Binary_tlElongsPlonggR.tagnum = -1 ;
  G__G__VAMOScalibrationLN_KVCalibrator.tagnum = -1 ;
  G__G__VAMOScalibrationLN_KVSeDPositionCal.tagnum = -1 ;
  G__G__VAMOScalibrationLN_KVLightEnergyCsI.tagnum = -1 ;
  G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__VAMOScalibration() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TClass);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TObject);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TNamed);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_KVBase);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TF1);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_KVDetector);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_Binary_tlEunsignedsPchargR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_Binary_tlEunsignedsPshortgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_Binary_tlEunsignedsPintgR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_Binary_tlElongsPlonggR);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_KVCalibrator);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_KVSeDPositionCal),sizeof(KVSeDPositionCal),-1,324864,"Position calibration for SeD detectors of VAMOS",G__setup_memvarKVSeDPositionCal,G__setup_memfuncKVSeDPositionCal);
   G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_KVLightEnergyCsI);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G__VAMOScalibrationLN_KVLightEnergyCsIVamos),sizeof(KVLightEnergyCsIVamos),-1,324864,"Specific light-Energy Function for Vamos CsI   ",G__setup_memvarKVLightEnergyCsIVamos,G__setup_memfuncKVLightEnergyCsIVamos);
}
extern "C" void G__cpp_setupG__VAMOScalibration(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__VAMOScalibration()");
  G__set_cpp_environmentG__VAMOScalibration();
  G__cpp_setup_tagtableG__VAMOScalibration();

  G__cpp_setup_inheritanceG__VAMOScalibration();

  G__cpp_setup_typetableG__VAMOScalibration();

  G__cpp_setup_memvarG__VAMOScalibration();

  G__cpp_setup_memfuncG__VAMOScalibration();
  G__cpp_setup_globalG__VAMOScalibration();
  G__cpp_setup_funcG__VAMOScalibration();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__VAMOScalibration();
  return;
}
class G__cpp_setup_initG__VAMOScalibration {
  public:
    G__cpp_setup_initG__VAMOScalibration() { G__add_setup_func("G__VAMOScalibration",(G__incsetup)(&G__cpp_setupG__VAMOScalibration)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__VAMOScalibration() { G__remove_setup_func("G__VAMOScalibration"); }
};
G__cpp_setup_initG__VAMOScalibration G__cpp_setup_initializerG__VAMOScalibration;

