/********************************************************************
* G__FAZIAidentification.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__FAZIAidentification.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__FAZIAidentification();
extern void G__cpp_setup_inheritanceG__FAZIAidentification();
extern void G__cpp_setup_typetableG__FAZIAidentification();
extern void G__cpp_setup_memvarG__FAZIAidentification();
extern void G__cpp_setup_globalG__FAZIAidentification();
extern void G__cpp_setup_memfuncG__FAZIAidentification();
extern void G__cpp_setup_funcG__FAZIAidentification();
extern void G__set_cpp_environmentG__FAZIAidentification();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVFAZIAIDSiSi.h"
#include "KVFAZIAIDTelescope.h"
#include "KVFAZIAIDSiPSA.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__FAZIAidentificationLN_TClass;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TBuffer;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMemberInspector;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TObject;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TNamed;
extern G__linked_taginfo G__G__FAZIAidentificationLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVBase;
extern G__linked_taginfo G__G__FAZIAidentificationLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVNucleus;
extern G__linked_taginfo G__G__FAZIAidentificationLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__FAZIAidentificationLN_TGraph;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVIdentificationResult;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVIDTelescope;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVFAZIAIDTelescope;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVIDZAGrid;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVFAZIAIDSiSi;
extern G__linked_taginfo G__G__FAZIAidentificationLN_KVFAZIAIDSiPSA;

/* STUB derived class for protected member access */
