#!/bin/bash
# $1 = CMAKE_CURRENT_SOURCE_DIR
# $2 = CMAKE_CURRENT_BINARY_DIR
# $3 = CMAKE_FORTRAN_COMPILER

echo $1
echo $2
compil=$3
echo "Compilateur fortran -> $compil"
lcampagne="1 2 4"

indra_throng=$THRONG_DIR

for campagne in $lcampagne
do
	VEDA_LIB=$indra_throng/lib/veda$campagne
	
	if [ ! -d $VEDA_LIB ]
	then 
		echo "Repertoire $VEDA_LIB created"
		mkdir $VEDA_LIB
	fi
	
	if [ $campagne == 1 ]
	then
		VEDA_INC=$indra_throng"/veda1/for"
	
	elif [ $campagne == 2 ]
	then
		VEDA_INC=$indra_throng"/veda2/for2"
	elif [ $campagne == 4 ]
	then
		VEDA_INC=$indra_throng"/veda4/for/include"
	else
		exit
	fi
	
	rep_sup=$1/fortran_lecture_dst/supp_camp$campagne
	if [ -d $rep_sup ]
	then
		echo "$rep_sup existe"
		lib_sup=libkali_camp"$campagne"_sup.a
		lpointo=""
		for sup in $rep_sup/*.f
		do
			echo $sup
			$compil -w -I$VEDA_INC $sup -c
			rac=`basename $sup .f`
			echo "$rac.o"
			lpointo="$lpointo $rac.o"
		done	
		ar qv $lib_sup $lpointo
		mv $lib_sup $KVROOT/lib/
		rm $lpointo
		echo $lpointo
		cd ../
	else
		echo "pas de supp_camp"$campagne""
	fi
	
	$compil -w -I$VEDA_INC -fno-range-check $1/fortran_lecture_dst/kali_lecture_dst_camp$campagne.f -c
	mv $2/../kali_lecture_dst_camp$campagne.o $KVROOT/lib/

done

exit
