/********************************************************************
* G__KVIndradb.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__KVIndradb.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__KVIndradb();
extern void G__cpp_setup_inheritanceG__KVIndradb();
extern void G__cpp_setup_typetableG__KVIndradb();
extern void G__cpp_setup_memvarG__KVIndradb();
extern void G__cpp_setup_globalG__KVIndradb();
extern void G__cpp_setup_memfuncG__KVIndradb();
extern void G__cpp_setup_funcG__KVIndradb();
extern void G__set_cpp_environmentG__KVIndradb();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVDBElasticPeak.h"
#include "KVINDRAUpDater_e475s.h"
#include "KVINDRADB_e503.h"
#include "KVDB_BIC_Pressures.h"
#include "KVDBPeak.h"
#include "KVINDRADB_e416a.h"
#include "KVINDRARunSheetReader.h"
#include "KVDBAlphaPeak.h"
#include "KVINDRAUpDater_e613.h"
#include "KVINDRADB4.h"
#include "KVDBTape.h"
#include "KVINDRADBRun.h"
#include "KVDBChIoPressures.h"
#include "KVINDRAPulserDataTree.h"
#include "KVINDRARunListReader.h"
#include "KVINDRAUpDater_e416a.h"
#include "KVINDRADB2.h"
#include "KVINDRADB_e475s.h"
#include "KVINDRAUpDater.h"
#include "KVINDRADB_e613.h"
#include "KVINDRADB.h"
#include "KVINDRADB1.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__KVIndradbLN_TClass;
extern G__linked_taginfo G__G__KVIndradbLN_TBuffer;
extern G__linked_taginfo G__G__KVIndradbLN_TMemberInspector;
extern G__linked_taginfo G__G__KVIndradbLN_TObject;
extern G__linked_taginfo G__G__KVIndradbLN_TNamed;
extern G__linked_taginfo G__G__KVIndradbLN_TString;
extern G__linked_taginfo G__G__KVIndradbLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__KVIndradbLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__KVIndradbLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__KVIndradbLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVIndradbLN_TList;
extern G__linked_taginfo G__G__KVIndradbLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__KVIndradbLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVIndradbLN_TFolder;
extern G__linked_taginfo G__G__KVIndradbLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__KVIndradbLN_TFile;
extern G__linked_taginfo G__G__KVIndradbLN_THashTable;
extern G__linked_taginfo G__G__KVIndradbLN_KVSeqCollection;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBRecord;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBTable;
extern G__linked_taginfo G__G__KVIndradbLN_KVBase;
extern G__linked_taginfo G__G__KVIndradbLN_KVRList;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBParameterSet;
extern G__linked_taginfo G__G__KVIndradbLN_KVNumberList;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRARRMValidator;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBPeak;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBElasticPeak;
extern G__linked_taginfo G__G__KVIndradbLN_KVList;
extern G__linked_taginfo G__G__KVIndradbLN_KVDataBase;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__KVIndradbLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__KVIndradbLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__KVIndradbLN_TH1;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBSystem;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBRun;
extern G__linked_taginfo G__G__KVIndradbLN_KVUpDater;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRAUpDater;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRAUpDater_e475s;
extern G__linked_taginfo G__G__KVIndradbLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__KVIndradbLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBTape;
extern G__linked_taginfo G__G__KVIndradbLN_KVDatime;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADBRun;
extern G__linked_taginfo G__G__KVIndradbLN_KVDetector;
extern G__linked_taginfo G__G__KVIndradbLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__KVIndradbLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__KVIndradbLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__KVIndradbLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__KVIndradbLN_TTree;
extern G__linked_taginfo G__G__KVIndradbLN_KVRunListLine;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRARunListReader;
extern G__linked_taginfo G__G__KVIndradbLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__KVIndradbLN_KVTarArchive;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRAPulserDataTree;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB_e503;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBChIoPressures;
extern G__linked_taginfo G__G__KVIndradbLN_KVDB_BIC_Pressures;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB_e416a;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRARunSheetReader;
extern G__linked_taginfo G__G__KVIndradbLN_KVDBAlphaPeak;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRAUpDater_e613;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB4;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRAUpDater_e416a;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB2;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB_e475s;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB_e613;
extern G__linked_taginfo G__G__KVIndradbLN_KVINDRADB1;

/* STUB derived class for protected member access */
