/********************************************************************
* G__FAZIAparticles.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__FAZIAparticles.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__FAZIAparticles();
extern void G__cpp_setup_inheritanceG__FAZIAparticles();
extern void G__cpp_setup_typetableG__FAZIAparticles();
extern void G__cpp_setup_memvarG__FAZIAparticles();
extern void G__cpp_setup_globalG__FAZIAparticles();
extern void G__cpp_setup_memfuncG__FAZIAparticles();
extern void G__cpp_setup_funcG__FAZIAparticles();
extern void G__set_cpp_environmentG__FAZIAparticles();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVFAZIAReconNuc.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__FAZIAparticlesLN_TClass;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TBuffer;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMemberInspector;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TObject;
extern G__linked_taginfo G__G__FAZIAparticlesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_TLorentzVector;
extern G__linked_taginfo G__G__FAZIAparticlesLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_KVParticle;
extern G__linked_taginfo G__G__FAZIAparticlesLN_KVNucleus;
extern G__linked_taginfo G__G__FAZIAparticlesLN_KVDetector;
extern G__linked_taginfo G__G__FAZIAparticlesLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__FAZIAparticlesLN_KVReconstructedNucleus;
extern G__linked_taginfo G__G__FAZIAparticlesLN_KVFAZIAReconNuc;

/* STUB derived class for protected member access */
