//
// File generated by rootcint at Fri Jul 17 15:52:47 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME G__ClassTraj
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G__ClassTraj.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void ClassTraj_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_ClassTraj(void *p);
   static void deleteArray_ClassTraj(void *p);
   static void destruct_ClassTraj(void *p);
   static void streamer_ClassTraj(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::ClassTraj*)
   {
      ::ClassTraj *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ClassTraj >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ClassTraj", ::ClassTraj::Class_Version(), "/home/john/software/sources/kaliveda.git/KVMultiDet/examples/ClassTraj.h", 19,
                  typeid(::ClassTraj), ::ROOT::DefineBehavior(ptr, ptr),
                  &::ClassTraj::Dictionary, isa_proxy, 0,
                  sizeof(::ClassTraj) );
      instance.SetDelete(&delete_ClassTraj);
      instance.SetDeleteArray(&deleteArray_ClassTraj);
      instance.SetDestructor(&destruct_ClassTraj);
      instance.SetStreamerFunc(&streamer_ClassTraj);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::ClassTraj*)
   {
      return GenerateInitInstanceLocal((::ClassTraj*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ClassTraj*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr ClassTraj::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *ClassTraj::Class_Name()
{
   return "ClassTraj";
}

//______________________________________________________________________________
const char *ClassTraj::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::ClassTraj*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ClassTraj::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::ClassTraj*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ClassTraj::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::ClassTraj*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ClassTraj::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::ClassTraj*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void ClassTraj::Streamer(TBuffer &R__b)
{
   // Stream an object of class ClassTraj.

   KVRungeKutta::Streamer(R__b);
}

//______________________________________________________________________________
void ClassTraj::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ClassTraj.
      TClass *R__cl = ::ClassTraj::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*coords", &coords);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*RP", &RP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*RT", &RT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*VP", &VP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*VT", &VT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RCM[2]", RCM);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "VCM[2]", VCM);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWilcke", &fWilcke);
      R__insp.InspectMember(fWilcke, "fWilcke.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ELAB", &ELAB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E0", &E0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "alpha", &alpha);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ProjARC", &ProjARC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TargARC", &TargARC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ProjTRAJ", &ProjTRAJ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nTRAJPoints", &nTRAJPoints);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*CMPositionPad", &CMPositionPad);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*infox", &infox);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ProjARClab", &ProjARClab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TargARClab", &TargARClab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ProjTRAJlab", &ProjTRAJlab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*LabPositionPad", &LabPositionPad);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nTRAJPointslab", &nTRAJPointslab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "minDist", &minDist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EtotDeb", &EtotDeb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EtotFin", &EtotFin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TKEL", &TKEL);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TKE", &TKE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "VPOT", &VPOT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ThetaProjLab", &ThetaProjLab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "absThetaProjLab", &absThetaProjLab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EProjLab", &EProjLab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ImpactParameter", &ImpactParameter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "AngMom", &AngMom);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RotationAngle", &RotationAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fused", &fused);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inelastic", &inelastic);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "incoming", &incoming);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "interacting", &interacting);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "outgoing", &outgoing);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tcon", &tcon);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tsep", &tsep);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RotationTime", &RotationTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "randomX", &randomX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sysName", &sysName);
      R__insp.InspectMember(sysName, "sysName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "colName", &colName);
      R__insp.InspectMember(colName, "colName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*theFile", &theFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*theTree", &theTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fVisualization", &fVisualization);
      KVRungeKutta::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_ClassTraj(void *p) {
      delete ((::ClassTraj*)p);
   }
   static void deleteArray_ClassTraj(void *p) {
      delete [] ((::ClassTraj*)p);
   }
   static void destruct_ClassTraj(void *p) {
      typedef ::ClassTraj current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ClassTraj(TBuffer &buf, void *obj) {
      ((::ClassTraj*)obj)->::ClassTraj::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::ClassTraj

/********************************************************
* G__ClassTraj.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG__ClassTraj();

extern "C" void G__set_cpp_environmentG__ClassTraj() {
  G__cpp_reset_tagtableG__ClassTraj();
}
#include <new>
extern "C" int G__cpp_dllrevG__ClassTraj() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ClassTraj */
static int G__G__ClassTraj_693_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ClassTraj* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ClassTraj(
*(KVNucleus*) libp->para[0].ref, *(KVNucleus*) libp->para[1].ref
, (Bool_t) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) ClassTraj(
*(KVNucleus*) libp->para[0].ref, *(KVNucleus*) libp->para[1].ref
, (Bool_t) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ClassTraj(*(KVNucleus*) libp->para[0].ref, *(KVNucleus*) libp->para[1].ref);
     } else {
       p = new((void*) gvp) ClassTraj(*(KVNucleus*) libp->para[0].ref, *(KVNucleus*) libp->para[1].ref);
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((ClassTraj*) G__getstructoffset())->SetViz((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((ClassTraj*) G__getstructoffset())->SetViz();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((ClassTraj*) G__getstructoffset())->InitTrajectory((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((ClassTraj*) G__getstructoffset())->InitTrajectory((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const ClassTraj*) G__getstructoffset())->dr((Double_t*) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const ClassTraj*) G__getstructoffset())->dv((Double_t*) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const ClassTraj*) G__getstructoffset())->dr_x((Double_t*) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const ClassTraj*) G__getstructoffset())->dr_y((Double_t*) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const ClassTraj*) G__getstructoffset())->dv_x((Double_t*) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const ClassTraj*) G__getstructoffset())->dv_y((Double_t*) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClassTraj*) G__getstructoffset())->UpdateARCPositions((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ClassTraj*) G__getstructoffset())->ThetaLabProj());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ClassTraj*) G__getstructoffset())->ELabProj());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ClassTraj*) G__getstructoffset())->TotalAngularMomentum());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const ClassTraj*) G__getstructoffset())->TotalEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClassTraj*) G__getstructoffset())->Run((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClassTraj*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClassTraj*) G__getstructoffset())->UpdateInfos((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 8:
      ((ClassTraj*) G__getstructoffset())->CalcTrajectories(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6]), (Double_t) G__double(libp->para[7]));
      G__setnull(result7);
      break;
   case 7:
      ((ClassTraj*) G__getstructoffset())->CalcTrajectories(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 8:
      ((ClassTraj*) G__getstructoffset())->CalcTrajectories(
(Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6]), (Double_t) G__double(libp->para[7]));
      G__setnull(result7);
      break;
   case 7:
      ((ClassTraj*) G__getstructoffset())->CalcTrajectories(
(Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClassTraj*) G__getstructoffset())->InitTree((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClassTraj*) G__getstructoffset())->DoOneTraj((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ClassTraj::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClassTraj::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ClassTraj::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ClassTraj::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ClassTraj*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClassTraj::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClassTraj::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClassTraj::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ClassTraj_693_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClassTraj::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__ClassTraj_693_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ClassTraj* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ClassTraj(*(ClassTraj*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ClassTraj G__TClassTraj;
static int G__G__ClassTraj_693_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ClassTraj*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ClassTraj*) (soff+(sizeof(ClassTraj)*i)))->~G__TClassTraj();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ClassTraj*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ClassTraj*) (soff))->~G__TClassTraj();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__ClassTraj_693_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ClassTraj* dest = (ClassTraj*) G__getstructoffset();
   *dest = *(ClassTraj*) libp->para[0].ref;
   const ClassTraj& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ClassTraj */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__ClassTraj {
 public:
  G__Sizep2memfuncG__ClassTraj(): p(&G__Sizep2memfuncG__ClassTraj::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__ClassTraj::*p)();
};

size_t G__get_sizep2memfuncG__ClassTraj()
{
  G__Sizep2memfuncG__ClassTraj a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__ClassTraj() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj))) {
     ClassTraj *G__Lderived;
     G__Lderived=(ClassTraj*)0x1000;
     {
       KVRungeKutta *G__Lpbase=(KVRungeKutta*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj),G__get_linked_tagnum(&G__G__ClassTrajLN_KVRungeKutta),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       KVBase *G__Lpbase=(KVBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj),G__get_linked_tagnum(&G__G__ClassTrajLN_KVBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj),G__get_linked_tagnum(&G__G__ClassTrajLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj),G__get_linked_tagnum(&G__G__ClassTrajLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__ClassTraj() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__G__ClassTrajLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__G__ClassTrajLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ClassTraj */
static void G__setup_memvarClassTraj(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj));
   { ClassTraj *p; p=(ClassTraj*)0x1000; if (p) { }
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"coords=",0,(char*)NULL);
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"RP=",0,(char*)NULL);
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"RT=",0,(char*)NULL);
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"VP=",0,(char*)NULL);
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"VT=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"RCM[2]=",0,"! position of centre of mass");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"VCM[2]=",0,"! velocity of centre of mass");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_KVWilckeReactionParameters),-1,-1,4,"fWilcke=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"ELAB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"E0=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"alpha=",0,"friction parameter");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TArc),-1,-1,4,"ProjARC=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TArc),-1,-1,4,"TargARC=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TGraph),-1,-1,4,"ProjTRAJ=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nTRAJPoints=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TCanvas),-1,-1,4,"CMPositionPad=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TLatex),-1,-1,4,"infox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TArc),-1,-1,4,"ProjARClab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TArc),-1,-1,4,"TargARClab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TGraph),-1,-1,4,"ProjTRAJlab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TCanvas),-1,-1,4,"LabPositionPad=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nTRAJPointslab=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"minDist=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"EtotDeb=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"EtotFin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"TKEL=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"TKE=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"VPOT=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"ThetaProjLab=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"absThetaProjLab=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"EProjLab=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"ImpactParameter=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"AngMom=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"RotationAngle=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fused=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"inelastic=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"incoming=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"interacting=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"outgoing=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"tcon=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"tsep=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"RotationTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"randomX=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TString),-1,-1,4,"sysName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TString),-1,-1,4,"colName=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TFile),-1,-1,4,"theFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TTree),-1,-1,4,"theTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fVisualization=",0,"true = show trajectories");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__ClassTrajLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__ClassTraj() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncClassTraj(void) {
   /* ClassTraj */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj));
   G__memfunc_setup("ClassTraj",903,G__G__ClassTraj_693_0_1, 105, G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj), -1, 0, 3, 1, 1, 0, 
"u 'KVNucleus' - 11 - proj u 'KVNucleus' - 11 - targ "
"g - 'Bool_t' 0 'kTRUE' viz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetViz",613,G__G__ClassTraj_693_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 'kTRUE' on", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitTrajectory",1467,G__G__ClassTraj_693_0_3, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - b d - 'Double_t' 0 - e "
"d - 'Double_t' 0 '0' a", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dr",214,G__G__ClassTraj_693_0_4, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"D - 'Double_t' 0 - rp D - 'Double_t' 0 - rt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dv",218,G__G__ClassTraj_693_0_5, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"D - 'Double_t' 0 - vp D - 'Double_t' 0 - vt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dr_x",429,G__G__ClassTraj_693_0_6, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"D - 'Double_t' 0 - rp D - 'Double_t' 0 - rt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dr_y",430,G__G__ClassTraj_693_0_7, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"D - 'Double_t' 0 - rp D - 'Double_t' 0 - rt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dv_x",433,G__G__ClassTraj_693_0_8, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"D - 'Double_t' 0 - vp D - 'Double_t' 0 - vt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dv_y",434,G__G__ClassTraj_693_0_9, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 8, 
"D - 'Double_t' 0 - vp D - 'Double_t' 0 - vt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateARCPositions",1793,G__G__ClassTraj_693_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ThetaLabProj",1184,G__G__ClassTraj_693_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ELabProj",751,G__G__ClassTraj_693_0_12, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TotalAngularMomentum",2080,G__G__ClassTraj_693_0_13, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TotalEnergy",1134,G__G__ClassTraj_693_0_14, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcDerivs",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - - D - 'Double_t' 0 - - "
"D - 'Double_t' 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Run",309,G__G__ClassTraj_693_0_16, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - tmin d - 'Double_t' 0 - tmax "
"d - 'Double_t' 0 - dt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__G__ClassTraj_693_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateInfos",1122,G__G__ClassTraj_693_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - b d - 'Double_t' 0 - time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcTrajectories",1634,G__G__ClassTraj_693_0_19, 121, -1, -1, 0, 8, 1, 1, 0, 
"d - 'Double_t' 0 - e d - 'Double_t' 0 - bmin "
"d - 'Double_t' 0 - bmax d - 'Double_t' 0 - db "
"d - 'Double_t' 0 - tmin d - 'Double_t' 0 - tmax "
"d - 'Double_t' 0 - dt d - 'Double_t' 0 '0' friction", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcTrajectories",1634,G__G__ClassTraj_693_0_20, 121, -1, -1, 0, 8, 1, 1, 0, 
"d - 'Double_t' 0 - e i - 'Int_t' 0 - ntraj "
"d - 'Double_t' 0 - bmin d - 'Double_t' 0 - bmax "
"d - 'Double_t' 0 - tmin d - 'Double_t' 0 - tmax "
"d - 'Double_t' 0 - dt d - 'Double_t' 0 '0' friction", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitTree",804,G__G__ClassTraj_693_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoOneTraj",870,G__G__ClassTraj_693_0_22, 121, -1, -1, 0, 6, 1, 1, 0, 
"d - 'Double_t' 0 - tmin d - 'Double_t' 0 - friction "
"d - 'Double_t' 0 - b d - 'Double_t' 0 - e "
"d - 'Double_t' 0 - tmax d - 'Double_t' 0 - dt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__G__ClassTraj_693_0_23, 85, G__get_linked_tagnum(&G__G__ClassTrajLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ClassTraj::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__ClassTraj_693_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ClassTraj::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__ClassTraj_693_0_25, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ClassTraj::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__ClassTraj_693_0_26, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ClassTraj::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__ClassTrajLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__ClassTraj_693_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__ClassTraj_693_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ClassTraj::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__ClassTraj_693_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ClassTraj::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__ClassTraj_693_0_33, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ClassTraj::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__ClassTraj_693_0_34, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ClassTraj::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ClassTraj", 903, G__G__ClassTraj_693_0_35, (int) ('i'), G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj), -1, 0, 1, 1, 1, 0, "u 'ClassTraj' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ClassTraj", 1029, G__G__ClassTraj_693_0_36, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__ClassTraj_693_0_37, (int) ('u'), G__get_linked_tagnum(&G__G__ClassTrajLN_ClassTraj), -1, 1, 1, 1, 1, 0, "u 'ClassTraj' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__ClassTraj() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__ClassTraj() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__ClassTraj() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__ClassTrajLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_KVBase = { "KVBase" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_KVRungeKutta = { "KVRungeKutta" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__G__ClassTrajLN_KVNucleus = { "KVNucleus" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_KVWilckeReactionParameters = { "KVWilckeReactionParameters" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TArc = { "TArc" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_TLatex = { "TLatex" , 99 , -1 };
G__linked_taginfo G__G__ClassTrajLN_ClassTraj = { "ClassTraj" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__ClassTraj() {
  G__G__ClassTrajLN_TClass.tagnum = -1 ;
  G__G__ClassTrajLN_TBuffer.tagnum = -1 ;
  G__G__ClassTrajLN_TMemberInspector.tagnum = -1 ;
  G__G__ClassTrajLN_TObject.tagnum = -1 ;
  G__G__ClassTrajLN_TNamed.tagnum = -1 ;
  G__G__ClassTrajLN_TString.tagnum = -1 ;
  G__G__ClassTrajLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G__ClassTrajLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__ClassTrajLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__G__ClassTrajLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__ClassTrajLN_KVBase.tagnum = -1 ;
  G__G__ClassTrajLN_KVRungeKutta.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__G__ClassTrajLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__G__ClassTrajLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__G__ClassTrajLN_TFile.tagnum = -1 ;
  G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__G__ClassTrajLN_KVNucleus.tagnum = -1 ;
  G__G__ClassTrajLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__G__ClassTrajLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__ClassTrajLN_TCanvas.tagnum = -1 ;
  G__G__ClassTrajLN_KVWilckeReactionParameters.tagnum = -1 ;
  G__G__ClassTrajLN_TArc.tagnum = -1 ;
  G__G__ClassTrajLN_TGraph.tagnum = -1 ;
  G__G__ClassTrajLN_TTree.tagnum = -1 ;
  G__G__ClassTrajLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__G__ClassTrajLN_TLatex.tagnum = -1 ;
  G__G__ClassTrajLN_ClassTraj.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__ClassTraj() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TClass);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TObject);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TNamed);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TString);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_KVBase);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_KVRungeKutta);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TFile);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_KVNucleus);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_KVWilckeReactionParameters);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TArc);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TGraph);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TTree);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_TLatex);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G__ClassTrajLN_ClassTraj),sizeof(ClassTraj),-1,62464,"Classical trajectory for heavy ion collisions",G__setup_memvarClassTraj,G__setup_memfuncClassTraj);
}
extern "C" void G__cpp_setupG__ClassTraj(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__ClassTraj()");
  G__set_cpp_environmentG__ClassTraj();
  G__cpp_setup_tagtableG__ClassTraj();

  G__cpp_setup_inheritanceG__ClassTraj();

  G__cpp_setup_typetableG__ClassTraj();

  G__cpp_setup_memvarG__ClassTraj();

  G__cpp_setup_memfuncG__ClassTraj();
  G__cpp_setup_globalG__ClassTraj();
  G__cpp_setup_funcG__ClassTraj();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__ClassTraj();
  return;
}
class G__cpp_setup_initG__ClassTraj {
  public:
    G__cpp_setup_initG__ClassTraj() { G__add_setup_func("G__ClassTraj",(G__incsetup)(&G__cpp_setupG__ClassTraj)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__ClassTraj() { G__remove_setup_func("G__ClassTraj"); }
};
G__cpp_setup_initG__ClassTraj G__cpp_setup_initializerG__ClassTraj;

