/********************************************************************
* G__KVMultiDetdata_management.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__KVMultiDetdata_management.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__KVMultiDetdata_management();
extern void G__cpp_setup_inheritanceG__KVMultiDetdata_management();
extern void G__cpp_setup_typetableG__KVMultiDetdata_management();
extern void G__cpp_setup_memvarG__KVMultiDetdata_management();
extern void G__cpp_setup_globalG__KVMultiDetdata_management();
extern void G__cpp_setup_memfuncG__KVMultiDetdata_management();
extern void G__cpp_setup_funcG__KVMultiDetdata_management();
extern void G__set_cpp_environmentG__KVMultiDetdata_management();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVDataRepository.h"
#include "KVDataAnalysisTask.h"
#include "KVDMSDataRepository.h"
#include "KVDataSet.h"
#include "SRB.h"
#include "IRODSDataRepository.h"
#include "KVDataSetManager.h"
#include "DMSAvailableRunsFile.h"
#include "SRBDataRepository.h"
#include "KVDataRepositoryManager.h"
#include "KVRemoteAvailableRunsFile.h"
#include "IRODS.h"
#include "KVDMS.h"
#include "KVRemoteDataRepository.h"
#include "KVRemoteDataSetManager.h"
#include "KVSimDir.h"
#include "KVSimFile.h"
#include "KVAvailableRunsFile.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TClass;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TBuffer;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TMemberInspector;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TObject;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TNamed;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TString;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TList;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVString;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVLockfile;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVBase;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TSystem;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TSeqCollection;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_FileStat_t;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TDatime;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVNumberList;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVList;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDatime;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_TFile;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVSeqCollection;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDataBase;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDataSetManager;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDataRepository;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDBSystem;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDataAnalysisTask;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVAvailableRunsFile;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDataSet;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDataSetcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVHashList;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVNameValueList;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVUniqueNameList;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDMS;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDMSDataRepository;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_DMSFile_t;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_SRB;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_IRODSDataRepository;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_DMSAvailableRunsFile;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_SRBDataRepository;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVDataRepositoryManager;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVRemoteAvailableRunsFile;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_IRODS;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVRemoteDataRepository;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVRemoteDataSetManager;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVSimDir;
extern G__linked_taginfo G__G__KVMultiDetdata_managementLN_KVSimFile;

/* STUB derived class for protected member access */
