/********************************************************************
* G__VAMOSbase.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__VAMOSbase.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__VAMOSbase();
extern void G__cpp_setup_inheritanceG__VAMOSbase();
extern void G__cpp_setup_typetableG__VAMOSbase();
extern void G__cpp_setup_memvarG__VAMOSbase();
extern void G__cpp_setup_globalG__VAMOSbase();
extern void G__cpp_setup_memfuncG__VAMOSbase();
extern void G__cpp_setup_funcG__VAMOSbase();
extern void G__set_cpp_environmentG__VAMOSbase();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Random.h"
#include "LogFile.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__VAMOSbaseLN_TClass;
extern G__linked_taginfo G__G__VAMOSbaseLN_TBuffer;
extern G__linked_taginfo G__G__VAMOSbaseLN_TMemberInspector;
extern G__linked_taginfo G__G__VAMOSbaseLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__VAMOSbaseLN_string;
extern G__linked_taginfo G__G__VAMOSbaseLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__VAMOSbaseLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSbaseLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__VAMOSbaseLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__VAMOSbaseLN_Random;
extern G__linked_taginfo G__G__VAMOSbaseLN_LogFile;

/* STUB derived class for protected member access */
