/********************************************************************
* G__KVMultiDetgeometry.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__KVMultiDetgeometry.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__KVMultiDetgeometry();
extern void G__cpp_setup_inheritanceG__KVMultiDetgeometry();
extern void G__cpp_setup_typetableG__KVMultiDetgeometry();
extern void G__cpp_setup_memvarG__KVMultiDetgeometry();
extern void G__cpp_setup_globalG__KVMultiDetgeometry();
extern void G__cpp_setup_memfuncG__KVMultiDetgeometry();
extern void G__cpp_setup_funcG__KVMultiDetgeometry();
extern void G__set_cpp_environmentG__KVMultiDetgeometry();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "KVLayer.h"
#include "KVTelescope.h"
#include "KVCalibrator.h"
#include "KVGroup.h"
#include "KVRangeTableGeoNavigator.h"
#include "KVGeoDetectorNode.h"
#include "KVASGroup.h"
#include "KVRing.h"
#include "KVDetector.h"
#include "KVGeoNavigator.h"
#include "KVACQParam.h"
#include "KVGeoStrucElement.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TClass;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TBuffer;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMemberInspector;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TObject;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TNamed;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TString;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TList;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TClonesArray;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVString;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVBase;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVSeqCollection;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVUniqueNameList;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVList;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TF1;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TVector3;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVIonRangeTable;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVNucleus;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TGeoVolume;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVMaterial;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVMaterialcLcLSolType;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TGeoHMatrix;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TGeoBBox;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVPosition;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TEnv;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVNameValueList;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVDetector;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVACQParam;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_Binary_tlEunsignedsPchargR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_Binary_tlEunsignedsPshortgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_Binary_tlEunsignedsPintgR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_Binary_tlElongsPlonggR;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVGeoDetectorNode;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVGeoStrucElement;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVGroup;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVCalibrator;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TGraph;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVDetectorcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVLayer;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVGroupcLcLdA;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVTelescope;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVEvent;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TGeoManager;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_TGeoNode;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVGeoNavigator;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVRangeTableGeoNavigator;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVASGroup;
extern G__linked_taginfo G__G__KVMultiDetgeometryLN_KVRing;

/* STUB derived class for protected member access */
